dual_ur:
# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    []
  left_arm_position_controller:
    type: position_controllers/JointPositionController
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
    gains:
      left_shoulder_pan_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      left_shoulder_lift_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      left_elbow_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      left_wrist_1_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      left_wrist_2_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      left_wrist_3_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
  right_arm_position_controller:
    type: position_controllers/JointPositionController
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
    gains:
      right_shoulder_pan_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_shoulder_lift_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_elbow_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_wrist_1_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_wrist_2_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_wrist_3_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1